UNAUTHORIZED_ACCESS_LOG = 'Unauthorized access attempt by user ID: %s'
BOT_STOPPED_LOG = 'Bot stopped by user'
REDIS_GROUP_CREATED_LOG = 'Redis group created successfully'
MESSAGE_SENT_ERROR_LOG = 'Message sent error to user %s: %s'
MESSAGE_PROCESSING_ERROR_LOG = 'Error processing message %s: %s'
REDIS_STREAM_ERROR_LOG = 'Redis Stream error: %s'
CLIENT_INITIALIZED_LOG = 'APIClient initialized with base URL: %s'
RESPONSE_MESSAGE_LOG = 'Response message: %s'
PAGE_LOAD_ERROR_LOG = 'Loading error: %s'
PRICE_LOAD_ERROR_LOG = 'Price element not found for selector: %s'
NO_SELECTOR_ERROR_LOG = 'No price selector configured for URL: %s'
GET_PRICE_ERROR_LOG = 'Price receiving error %s: %s'
PRICE_NOT_FOUND_ERROR_LOG = 'Price not found for %s'
DECIMAL_ERROR_LOG = 'Converting to Decimal error for %s: %s'
PRICE_UPDATED_LOG = 'Price updated for %s: %s'
MESSAGE_SEND_ERROR_LOG = 'Message send error: %s'
DOCUMENT_UPDATE_ERROR_LOG = 'Document update error for %s: %s'
PRICE_NOT_CHANGED_LOG = 'Price not changed %s'
START_PRICE_UPDATE_LOG = '🚀 Starting price update job...'
PRODUCT_LIST_NOT_RECEIVED_LOG = 'Could not get product list from the database.'
PRODUCT_UPDATE_RESULT_LOG = (
    '✅ Update job finished. Successfully updated %s/%s products.'
)
SCHEDULER_START_LOG = 'Scheduler started successfully.'
JOB_EXISTS_LOG = 'Job %s exists.'
JOB_ADDED_LOG = 'Job %s added to scheduler.'
SCHEDULER_START_FAILED_LOG = 'Failed to start scheduler: %s'
